### ISSUE TITLE
Document need for id on script tag

### ISSUE THREAD

**Issue by meiqimichelle** [GSA/DAP-Gov-wide-GA-Code#6]
I was getting a console error when linking to the DAP. @konklone was kind enough to track down the issue as recorded [here](https://github.com/18F/doi-extractives-data/issues/192), and it seems like the fix is to provide an id to the script tag.

If this is the proper solution, can this be documented in the repo?

Thanks!

**Comment by konklone** [comment]
Any update on what the `id` tag is useful for? It's a surprising requirement, and makes the snippet HTML more brittle and specific than it otherwise would be.

**Comment by tdlowden** [comment]
As per the implementation guide found at http://www.digitalgov.gov/services/dap/analytics-tool-instructions/

"The script block is a regular HTML script block with a URL pointing to the script file to be loaded.
However, the inclusion of the following is rare:
○ an id for the script block (id="_fed_an_js_tag")
○ query string parameters used within the script
❖ The id for the script block is:
○ required so that the script can find the block efficiently.
○ Ids other than "_fed_an_js_tag"will not be recognized.
○ longer, begins with an underscore and refers to a js file so it is likely to be unique"
